Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-19.10"
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "pg.yml"
  end
  config.vm.provider "virtualbox" do |vb|
  end
    config.vm.network "forwarded_port", guest: 5432, host: 15432
    config.ssh.insert_key = false
end

