Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-19.10"
  host_user = ENV['USER'] || ENV['USERNAME']
  vm_name = Dir.pwd.split(File::SEPARATOR).last
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "dev.yml"
  end
  config.vm.provider "virtualbox" do |vb|
     vb.memory = 8128
     vb.name = vm_name
     vb.linked_clone = true
     vb.customize ["modifyvm", :id, "--vram", "96"]
     vb.gui = true
     # vb.customize ["modifyvm", :id, "--monitorcount", "2"]
  end
    config.vm.hostname = vm_name
    config.vm.network "private_network", ip: '192.168.32.32'
    # Enable ssh forward agent
    config.ssh.forward_agent = true
    config.ssh.forward_x11 = true
    config.ssh.insert_key = false
    # this_dir = File.dirname(__FILE__)
    # config.vm.synced_folder(File.join(this_dir, '..'), '/Host')
end

