version: '3'
services:
 db:
  image: postgis/postgis:16-master
  container_name: postgis_container
  restart: always
  environment:
   POSTGRES_DB: official
   POSTGRES_USER: pgdocker
   POSTGRES_PASSWORD: pgdocker 
  ports:
      - '15432:5432'
  volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
