---
title: "Standard Analytics"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical-layout: fill
    theme: bootstrap
    logo: logo.jpg
    favicon: favicon.ico
runtime: shiny

---
<style>                     
.navbar {
  background-color:#2db8c5;
  border-color:black;
}
.navbar-brand {
color:black!important;
}
.section.sidebar {
  background-color: #2db8c5;
}
</style>

```{r global, include=FALSE}
library(flexdashboard)
library(ggplot2)
library(shiny)
library(lubridate)
library(curl)
library(jsonlite)
wdays_local <- c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday")
con <- curl("http://localhost:8181/customer_ids")
customer_ids <- fromJSON(con)
month_start <- function(x) {
x <- as.POSIXlt(x)
  x$mday <- 1
  as.POSIXct(x)}
this_month_start <- as.POSIXct(month_start(Sys.Date()))
three_months_ago <- as.POSIXct(this_month_start %m-% months(3), "%Y-%m-%d") 
```

Inputs {.sidebar data-width=160} 
--------------------------------------------

### Customer


```{r}
selectInput("chosen_customer_id", "Customer ID:", customer_ids, width = 150, selected=23)
```

### Date

Enter a date range in the box below

```{r}
dateRangeInput("date_range", "Date range:",
                 start  = three_months_ago,
                 min    = "2019-09-01",
                 max    = "2020-03-31",
                 format = "dd/mm/yyyy",
                 separator = " - ", autoclose=FALSE, width = 150)
```



```{r include=FALSE}
chosen_start <- reactive({as.POSIXct(input$date_range[1])})
chosen_end <- reactive({as.POSIXct(input$date_range[2])})

standard_analytics <- reactive({
  con <- curl(paste("http://localhost:8181/standard_analytics?customer_id=",
            as.character(input$chosen_customer_id), "&this_month_start=", this_month_start,
            "&chosen_start=", chosen_start(), "&chosen_end=", chosen_end(),
            "&three_months_ago=", three_months_ago, sep=""))
customer_data <- fromJSON(con)
return(customer_data)
})

```

This month annotation {data-height=10}
-------------------------------------

This month

This month {data-height=100}
-------------------------------------

### New Registrations

```{r}

renderValueBox({
  valueBox(prettyNum(standard_analytics()$this_month[1], big.mark = ","), 
           caption="New registrations",
           icon="ion-person-add",
           color="#2db8c5")
    })
```


### Unique Devices

```{r}

renderValueBox({
  valueBox(prettyNum(standard_analytics()$this_month[2], big.mark = ","), 
           caption="Unique devices", 
           icon="ion-android-phone-portrait", 
           color="#fdc300")
    })
```


### Sessions

```{r}
renderValueBox({
  valueBox(prettyNum(standard_analytics()$this_month[3], big.mark = ","), 
           caption="Device sessions", 
           icon="ion-ios-bolt", 
           color="#2daa56")
    })
```


### Downloaded Data

```{r}
renderValueBox({
  valueBox(paste(prettyNum(standard_analytics()$this_month[4], big.mark = ","), "Gb"),
           caption="Data usage", 
           icon="ion-ios-download-outline", 
           color="#fdc300")
    })
```


### Session Length

```{r}
renderValueBox({
  valueBox(paste(prettyNum(round(standard_analytics()$this_month[5], 0), big.mark = ","), "mins"),
           caption="Session Length", 
           icon="ion-clock", 
           color="#2db8c5")
    })
```

Chosen period annotation {data-height=10}
-------------------------------------

Chosen Time Period

Chosen Time Period 
----------------------------------------------------------

### New Registrations

```{r}
renderValueBox({
  valueBox(prettyNum(standard_analytics()$chosen_period[1], big.mark = ","), 
           caption="New registrations", 
           icon="ion-person-add", 
           color="#2db8c5")
    })
```

### Unique Devices

```{r}

renderValueBox({
  valueBox(prettyNum(standard_analytics()$chosen_period[2], big.mark = ","), 
           caption="Unique devices", 
           icon="ion-android-phone-portrait", 
           color="#fdc300")
    })
```

### Sessions

```{r}
renderValueBox({
  valueBox(prettyNum(standard_analytics()$chosen_period[3], big.mark = ","), 
           caption="Device sessions",
           icon="ion-ios-bolt", 
           color="#2daa56")
    })
```


### Data usage

```{r}
renderValueBox({
  valueBox(paste(prettyNum(standard_analytics()$chosen_period[4], big.mark = ","), "Gb"), 
           caption="Data usage",
           icon="ion-ios-download-outline",
           color="#fdc300")
    })
```

### Session time

```{r}
renderValueBox({
  valueBox(paste(prettyNum(round(standard_analytics()$chosen_period[5], 0), big.mark = ","), "mins"),
           caption="Session Length",
           icon="ion-clock",
           color="#2db8c5")
    })
```



Three month summaries {.tabset .tabset-fade}
------------------------------------------------------------------------------------------

### Registrations

```{r}
renderPlot({
  ggplot(standard_analytics()$monthly_reg_data, aes(x = monthno, y = n)) + 
    geom_bar(stat = "identity",position = "dodge", fill="#2db8c5") +
    labs(title = "Number of registrations", x = "Month", y = "Count") + 
    theme_bw()
    })
```


### Sessions

```{r}
renderPlot({
  ggplot(standard_analytics()$monthly_session_data,aes(x = monthno, y = n)) + 
    geom_bar(stat = "identity",position = "dodge", fill="#2daa56") +
    labs(title = "Number of sessions", x = "Month", y = "Count") + 
    theme_bw()
    }) 
```

### Data usage


```{r}
renderPlot({
  ggplot(standard_analytics()$dfm, aes(x = monthno, y = value)) + 
    geom_bar(aes(fill = variable),stat = "identity", position = "dodge") +
    scale_fill_manual(values = c("#2db8c5", "#fdc300"), name="",
                       breaks=c("total_downloaded_data_gb", "total_uploaded_data"),
                       labels=c("Downloaded", "Uploaded")) +
    labs(title = "Data usage", x = "Month", y = "Gb") + theme(legend.position="bottom") + 
    theme_bw()
    })
```

### Session time

```{r}
renderPlot({
  ggplot(standard_analytics()$monthly_session_times, aes(x = monthno, y = value)) + 
    geom_bar(stat = "identity",position = "dodge", fill="#2db8c5") +
    labs(title = "Total session time", x = "Month", y = "Minutes") + 
    theme_bw()
    })
```


