#!/bin/bash
set -eou pipefail
# evil conda hacks, needed to get conda.sh running in subshell
export PS1=
# shellcheck disable=SC1090
source "$HOME/miniconda3/etc/profile.d/conda.sh"
[ -z "$TEST_DATA_HOME" ] && echo "Need to set TEST_DATA_HOME" && exit 1
[ -z "$SPLUNK_QUERY_REPO" ] && echo "Need to set SPLUNK_QUERY_REPO" && exit 1
THISDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

function run_cmd(){
    local cmd=$1
    shift || true
    (
        "cmd_$cmd" "$@"
    )
}

function help(){
cat <<EOT
       Run commands for "$THISDIR"
           lint:             Run linters
           unit:             Run unit tests
           docker:           Run docker based sim tests
           splunk:           Run tests on splunk queries
           setup:            Install or update conda environment
           clean:            docker prune to get rid of containers and volumes
EOT
}

function main(){
    cmd=${1-default}
    shift || true
    case "$cmd" in
        help)
            help "$cmd"
            ;;
        default)
            run_cmd lint
            run_cmd unit
            run_cmd docker
            ;;
        lint|unit|docker|splunk)
            run_cmd "$cmd" "$@"
            ;;
        setup)
            run_cmd "$cmd" "$@"
            ;;
        clean)
            run_cmd "$cmd" "$@"
            ;;
         *)
            echo "There is no $cmd"
            ;;
    esac
}

function cmd_lint(){
    conda activate splunk
    cd "$THISDIR"
    mypy splunk/*.py
    mypy tests/*.py
    mypy docker_tests/*.py
    mypy splunk_tests/*.py
    mypy bin/*.py
    flake8 splunk/*.py
    flake8 docker_tests/*.py
    flake8 splunk_tests/*.py
    flake8 tests/*.py
    flake8 bin/*.py
    shellcheck "$THISDIR/run"
}

function cmd_unit(){
    conda activate splunk
    cd "$THISDIR"
    coverage run
    coverage report
    coverage html -d coverage_html
    coverage json -o .pycoverage.json
}


function cmd_docker(){
    conda activate splunk
    cd "$THISDIR"
    python -m pytest docker_tests/test_pytest.py
 }

function cmd_splunk(){
    conda activate splunk
    cd "$THISDIR"
    python -m pytest splunk_tests/
 }


function cmd_setup(){
    cd "$THISDIR"
    local target="$HOME/miniconda3/envs/splunk"
    if [[ ! -f "environment.yml" ]]; then
    echo "can't find environment.yml"
        exit 1
    fi
    if [[ -d "$target" ]]; then
    echo "Updating conda environment splunk"
    conda env update --prefix ./env --file environment.yml  --prune
    elif [[ ! -d "$target" ]]; then
    echo "Creating new conda environment 'splunk'"
    conda env create -f environment.yml
    fi
 }        

function cmd_clean(){
    docker system prune --volumes --force
}

main "$@"
