---
- hosts: all
  user: root
  tasks:
  - name: ensure curl present
    yum: 
      name: curl 
      state: present

  - name: get pip
    shell: |
      curl -O https://bootstrap.pypa.io/get-pip.py
      python get-pip.py

  - name: install virtualenv
    shell: pip install virtualenv

  - name: gitflow 1
    yum: 
      name: gitflow
    become: true

  - name: gitflow 2
    shell: git flow init

  - name: install IUS release package
    yum:
      name: "centos-release-scl"
      state: present
    become: true

  - name: install python
    yum: 
      name: "{{ packages }}"
    become: true
    vars:
      packages:
      - rh-python35
      - rh-python35-scldevel

  - name: activate python 3.5
    shell: scl enable rh-python35 bash

  - name: mysql
    yum: 
      name: "{{ packages }}"
    vars:
      packages:
      - mariadb-devel
    become: true

  - name: Gulp/sass/minify 1
    yum: 
      name: "{{ packages }}"
    vars:
       packages:
       - npm
       - ruby
       - ruby-devel
       - gcc
    become: true

  - name: pin rb-inotify
    shell: gem install rb-inotify -v 0.9.10

  - name: Gulp/sass/minify 2
    shell: gem install sass

  - name: set SECRET_KEY_CWA
    lineinfile:
      path: /home/vagrant/.bashrc
      line: 'export SECRET_KEY_CWA="#!sp030(u$1mcb&ufey%as5sy_xul+-k^dkeqk%z@uq)vu)u67"'
      insertafter: 'EOF'
      group: vagrant

  - name: set WERKZEUG_DEBUG_PIN
    lineinfile:
      path: /home/vagrant/.bashrc
      line: 'export WERKZEUG_DEBUG_PIN=off'
      insertafter: 'EOF'
      group: vagrant

  - name: set CWA_SPARK_API_BASEURL
    lineinfile:
      path: /home/vagrant/.bashrc
      line: 'export CWA_SPARK_API_BASEURL="https://spark-api-cwa-dev.wifispark.net"'
      insertafter: 'EOF'
      group: vagrant

  - name: set SECRET_KEY_CWA
    lineinfile:
      path: /home/vagrant/.bashrc
      line: 'export CWA_DB_PASSWORD="pass"'
      insertafter: 'EOF'
      group: vagrant

  - name: pillow dependencies
    yum:
         name: "{{ packages }}"
    vars:
       packages:
       - libtiff-devel
       - libjpeg-devel
       - libzip-devel
       - freetype-devel
       - lcms2-devel
       - libwebp-devel
       - tcl-devel
       - tk-devel
    become: true
