Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  host_user = ENV['USER'] || ENV['USERNAME']
  vm_name = Dir.pwd.split(File::SEPARATOR).last
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "cwa.yml"
  end
  config.vm.provider "virtualbox" do |vb|
     vb.memory = 2048
     vb.name = vm_name
     vb.linked_clone = true
  end
    config.vm.hostname = vm_name
    config.vm.network "private_network", ip: '192.168.33.33'
    # Enable ssh forward agent
    config.ssh.forward_agent = true
    config.ssh.forward_x11 = true
    config.ssh.insert_key = false
    # this_dir = File.dirname(__FILE__)
    # config.vm.synced_folder(File.join(this_dir, '..'), '/Host')
end

