#+CATEGORY: Calendar


* Mark Skelton's Zoom Meeting
  :PROPERTIES:
  :ETag:     "3182189618042000"
  :LOCATION: https://us02web.zoom.us/j/83722615875?pwd=VnUyVGQ5UG5mcVd2bm0wN2dsVjNhdz09
  :calendar-id: texhewson@gmail.com
  :ID:       _60q30c1g60o30e1i60o4ac1g60rj8gpl88rj2c1h84s34h9g60s30c1g60o30c1g70o4cc9g8d1kce9k6cr48dhg64o30c1g60o30c1g60o30c1g60o32c1g60o30c1g8gp46gi270pj0d9p6cpjgghk88s3ed1o60pj0cpi88p34c1i84qg_20200922T100000Z/texhewson@gmail.com
  :END:
:org-gcal:
<2020-09-22 Tue 11:00-11:45>

Mark Skelton is inviting you to a scheduled Zoom meeting.

Join Zoom Meeting
https://us02web.zoom.us/j/83722615875?pwd=VnUyVGQ5UG5mcVd2bm0wN2dsVjNhdz09

Meeting ID: 837 2261 5875
Password: Torbay

This email is confidential and intended solely for the use of the individual to whom it is addressed. Any views or opinions presented are solely those of the author and do not necessarily represent those of the Roman Catholic Diocese of Plymouth. If you are not the intended recipient, be advised that you have received this email in error and that any use, dissemination, forwarding, printing or copying of this email is strictly prohibited. If you have received this email in error please contact the sender.
:END:
* Mark Skelton's Zoom Meeting
  :PROPERTIES:
  :ETag:     "3182189618042000"
  :LOCATION: https://us02web.zoom.us/j/83722615875?pwd=VnUyVGQ5UG5mcVd2bm0wN2dsVjNhdz09
  :calendar-id: texhewson@gmail.com
  :ID:       _60q30c1g60o30e1i60o4ac1g60rj8gpl88rj2c1h84s34h9g60s30c1g60o30c1g70o4cc9g8d1kce9k6cr48dhg64o30c1g60o30c1g60o30c1g60o32c1g60o30c1g8gp46gi270pj0d9p6cpjgghk88s3ed1o60pj0cpi88p34c1i84qg_20201006T100000Z/texhewson@gmail.com
  :END:
:org-gcal:
<2020-10-06 Tue 11:00-11:45>

Mark Skelton is inviting you to a scheduled Zoom meeting.

Join Zoom Meeting
https://us02web.zoom.us/j/83722615875?pwd=VnUyVGQ5UG5mcVd2bm0wN2dsVjNhdz09

Meeting ID: 837 2261 5875
Password: Torbay

This email is confidential and intended solely for the use of the individual to whom it is addressed. Any views or opinions presented are solely those of the author and do not necessarily represent those of the Roman Catholic Diocese of Plymouth. If you are not the intended recipient, be advised that you have received this email in error and that any use, dissemination, forwarding, printing or copying of this email is strictly prohibited. If you have received this email in error please contact the sender.
:END:
* Mark Skelton's Zoom Meeting
  :PROPERTIES:
  :ETag:     "3182189618042000"
  :LOCATION: https://us02web.zoom.us/j/83722615875?pwd=VnUyVGQ5UG5mcVd2bm0wN2dsVjNhdz09
  :calendar-id: texhewson@gmail.com
  :ID:       _60q30c1g60o30e1i60o4ac1g60rj8gpl88rj2c1h84s34h9g60s30c1g60o30c1g70o4cc9g8d1kce9k6cr48dhg64o30c1g60o30c1g60o30c1g60o32c1g60o30c1g8gp46gi270pj0d9p6cpjgghk88s3ed1o60pj0cpi88p34c1i84qg_20201020T100000Z/texhewson@gmail.com
  :END:
:org-gcal:
<2020-10-20 Tue 11:00-11:45>

Mark Skelton is inviting you to a scheduled Zoom meeting.

Join Zoom Meeting
https://us02web.zoom.us/j/83722615875?pwd=VnUyVGQ5UG5mcVd2bm0wN2dsVjNhdz09

Meeting ID: 837 2261 5875
Password: Torbay

This email is confidential and intended solely for the use of the individual to whom it is addressed. Any views or opinions presented are solely those of the author and do not necessarily represent those of the Roman Catholic Diocese of Plymouth. If you are not the intended recipient, be advised that you have received this email in error and that any use, dissemination, forwarding, printing or copying of this email is strictly prohibited. If you have received this email in error please contact the sender.
:END:
* Mark Skelton's Zoom Meeting
  :PROPERTIES:
  :ETag:     "3182189618042000"
  :LOCATION: https://us02web.zoom.us/j/83722615875?pwd=VnUyVGQ5UG5mcVd2bm0wN2dsVjNhdz09
  :calendar-id: texhewson@gmail.com
  :ID:       _60q30c1g60o30e1i60o4ac1g60rj8gpl88rj2c1h84s34h9g60s30c1g60o30c1g70o4cc9g8d1kce9k6cr48dhg64o30c1g60o30c1g60o30c1g60o32c1g60o30c1g8gp46gi270pj0d9p6cpjgghk88s3ed1o60pj0cpi88p34c1i84qg_20201103T110000Z/texhewson@gmail.com
  :END:
:org-gcal:
<2020-11-03 Tue 11:00-11:45>

Mark Skelton is inviting you to a scheduled Zoom meeting.

Join Zoom Meeting
https://us02web.zoom.us/j/83722615875?pwd=VnUyVGQ5UG5mcVd2bm0wN2dsVjNhdz09

Meeting ID: 837 2261 5875
Password: Torbay

This email is confidential and intended solely for the use of the individual to whom it is addressed. Any views or opinions presented are solely those of the author and do not necessarily represent those of the Roman Catholic Diocese of Plymouth. If you are not the intended recipient, be advised that you have received this email in error and that any use, dissemination, forwarding, printing or copying of this email is strictly prohibited. If you have received this email in error please contact the sender.
:END:
* Mark Skelton's Zoom Meeting
  :PROPERTIES:
  :ETag:     "3182189618042000"
  :LOCATION: https://us02web.zoom.us/j/83722615875?pwd=VnUyVGQ5UG5mcVd2bm0wN2dsVjNhdz09
  :calendar-id: texhewson@gmail.com
  :ID:       _60q30c1g60o30e1i60o4ac1g60rj8gpl88rj2c1h84s34h9g60s30c1g60o30c1g70o4cc9g8d1kce9k6cr48dhg64o30c1g60o30c1g60o30c1g60o32c1g60o30c1g8gp46gi270pj0d9p6cpjgghk88s3ed1o60pj0cpi88p34c1i84qg_20201117T110000Z/texhewson@gmail.com
  :END:
:org-gcal:
<2020-11-17 Tue 11:00-11:45>

Mark Skelton is inviting you to a scheduled Zoom meeting.

Join Zoom Meeting
https://us02web.zoom.us/j/83722615875?pwd=VnUyVGQ5UG5mcVd2bm0wN2dsVjNhdz09

Meeting ID: 837 2261 5875
Password: Torbay

This email is confidential and intended solely for the use of the individual to whom it is addressed. Any views or opinions presented are solely those of the author and do not necessarily represent those of the Roman Catholic Diocese of Plymouth. If you are not the intended recipient, be advised that you have received this email in error and that any use, dissemination, forwarding, printing or copying of this email is strictly prohibited. If you have received this email in error please contact the sender.
:END:
* Fitness session
  :PROPERTIES:
  :ETag:     "3184610990572000"
  :calendar-id: texhewson@gmail.com
  :ID:       58hm49mlvogn2e1ar7udao9af8_20200922T113000Z/texhewson@gmail.com
  :END:
:org-gcal:
<2020-09-22 Tue 12:30-13:30>

<br>Join Zoom Meeting <br><a href="https://us04web.zoom.us/j/7044641874?pwd=RGJrM3pvcGJrdW1SSm0rcmlTc3ErQT09">https://us04web.zoom.us/j/<wbr>7044641874?pwd=<wbr>RGJrM3pvcGJrdW1SSm0rcmlTc3ErQT<wbr>09</a> <br><br>Meeting ID: 704 464 1874 <br>Password: 2pSbtY
:END:
* Fitness session
  :PROPERTIES:
  :ETag:     "3184610990572000"
  :calendar-id: texhewson@gmail.com
  :ID:       58hm49mlvogn2e1ar7udao9af8_20201006T113000Z/texhewson@gmail.com
  :END:
:org-gcal:
<2020-10-06 Tue 12:30-13:30>

<br>Join Zoom Meeting <br><a href="https://us04web.zoom.us/j/7044641874?pwd=RGJrM3pvcGJrdW1SSm0rcmlTc3ErQT09">https://us04web.zoom.us/j/<wbr>7044641874?pwd=<wbr>RGJrM3pvcGJrdW1SSm0rcmlTc3ErQT<wbr>09</a> <br><br>Meeting ID: 704 464 1874 <br>Password: 2pSbtY
:END:
* Fitness session
  :PROPERTIES:
  :ETag:     "3184610990572000"
  :calendar-id: texhewson@gmail.com
  :ID:       58hm49mlvogn2e1ar7udao9af8_20201020T113000Z/texhewson@gmail.com
  :END:
:org-gcal:
<2020-10-20 Tue 12:30-13:30>

<br>Join Zoom Meeting <br><a href="https://us04web.zoom.us/j/7044641874?pwd=RGJrM3pvcGJrdW1SSm0rcmlTc3ErQT09">https://us04web.zoom.us/j/<wbr>7044641874?pwd=<wbr>RGJrM3pvcGJrdW1SSm0rcmlTc3ErQT<wbr>09</a> <br><br>Meeting ID: 704 464 1874 <br>Password: 2pSbtY
:END:
* Fitness session
  :PROPERTIES:
  :ETag:     "3184610990572000"
  :calendar-id: texhewson@gmail.com
  :ID:       58hm49mlvogn2e1ar7udao9af8_20201103T123000Z/texhewson@gmail.com
  :END:
:org-gcal:
<2020-11-03 Tue 12:30-13:30>

<br>Join Zoom Meeting <br><a href="https://us04web.zoom.us/j/7044641874?pwd=RGJrM3pvcGJrdW1SSm0rcmlTc3ErQT09">https://us04web.zoom.us/j/<wbr>7044641874?pwd=<wbr>RGJrM3pvcGJrdW1SSm0rcmlTc3ErQT<wbr>09</a> <br><br>Meeting ID: 704 464 1874 <br>Password: 2pSbtY
:END:
* Fitness session
  :PROPERTIES:
  :ETag:     "3184610990572000"
  :calendar-id: texhewson@gmail.com
  :ID:       58hm49mlvogn2e1ar7udao9af8_20201117T123000Z/texhewson@gmail.com
  :END:
:org-gcal:
<2020-11-17 Tue 12:30-13:30>

<br>Join Zoom Meeting <br><a href="https://us04web.zoom.us/j/7044641874?pwd=RGJrM3pvcGJrdW1SSm0rcmlTc3ErQT09">https://us04web.zoom.us/j/<wbr>7044641874?pwd=<wbr>RGJrM3pvcGJrdW1SSm0rcmlTc3ErQT<wbr>09</a> <br><br>Meeting ID: 704 464 1874 <br>Password: 2pSbtY
:END:
* Uwe
  :PROPERTIES:
  :ETag:     "3199352130002000"
  :calendar-id: texhewson@gmail.com
  :ID:       c9im6ob5coo62b9h75imcb9kcdi30b9oc9j6ab9o6cp62oj1ccpj6d1o60/texhewson@gmail.com
  :END:
:org-gcal:
<2020-09-29 Tue 10:00-11:00>
:END:
* Teign Open Evening
  :PROPERTIES:
  :ETag:     "3201733012430000"
  :HANGOUTS: [[https://meet.google.com/fqz-ckmd-jfs][Join Hangouts Meet]]
  :calendar-id: texhewson@gmail.com
  :ID:       7m29nvoacfh85e1qik41d987h9/texhewson@gmail.com
  :END:
:org-gcal:
<2020-09-28 Mon 18:30-19:30>

https://teams.microsoft.com/dl/launcher/launcher.html?type=meetup-join&deeplinkId=f77f1775-ece9-4766-a9e2-bf8163080af0&directDl=true&msLaunch=true&enableMobilePage=true&url=%2F_%23%2Fl%2Fmeetup-join%2F19%3Ameeting_MDM4NWVmM2UtODhmOS00NzMzLTllNjctYmViNWE2ZWQ5MmM5@thread.v2%2F0%3Fcontext%3D%257b%2522Tid%2522%253a%25220c36f116-41e2-4d31-a0d6-699ae4627098%2522%252c%2522Oid%2522%253a%2522ff1c4a83-8492-47d6-b88e-6a8a64e2bafa%2522%252c%2522IsBroadcastMeeting%2522%253atrue%257d%26anon%3Dtrue&suppressPrompt=true
:END:
* Data Ethics SIG October
  :PROPERTIES:
  :ETag:     "3206406096452000"
  :LOCATION: Jitsi Meeting - https://meet.jit.si/AdjacentPlacesLabelLot
  :calendar-id: texhewson@gmail.com
  :ID:       02vvhtbrs1palv58hr03qpa3if/texhewson@gmail.com
  :END:
:org-gcal:
<2020-10-20 Tue 15:00-17:00>


Click the following link to join the meeting from your computer: https://meet.jit.si/AdjacentPlacesLabelLot

=====

Just want to dial in on your phone?

Call one of the following numbers: 
Australia: +61.8.7150.1136
Brazil: +55.21.3500.0112
Canada: +1.437.538.3987
France: +33.1.87.21.0005
Germany: +49.89.380.38719
Japan: +81.3.4510.2372
Netherlands: +31.85.208.1541
Spain: +34.932.205.409
Switzerland: +41.61.588.0496
UK: +44.203.885.2179
US: +1.512.647.1431

Dial your meeting ID: '1991261638' and you will be connected!
:END:
* Book Club
  :PROPERTIES:
  :ETag:     "3201894202652000"
  :calendar-id: texhewson@gmail.com
  :ID:       6m7e7112r4lkeact1kcleeammb/texhewson@gmail.com
  :END:
:org-gcal:
<2020-09-25 Fri 14:00-15:00>

<p><span><br></span><span>-<a>- Do not delete or change any of the following text. --</a></span><span><span><br><br></span></span><span><b><span>1.</span></b></span><a href="https://collaborate.webex.com/collaborate/j.php?MTID=mdbcd72b4fd4b9d215f6ffe1d3e22e919"><span><span>Click to Join the Meeting</span></span></a><span><span><br><br></span></span><span><b><span>IMPORTANT NOTICE: Please note that this Webex service allows audio and other information sent during the session to be recorded, which may be discoverable in a legal matter. By joining this session, you automatically consent to such recordings. If you do not consent to being recorded, discuss your concerns with the host or do not join the session.</span></b></span><span><span><br><br></span></span><span><b><span>2. Join the Audio</span></b></span></p><ul><li><span><span>From a Pfizer office - select Call Me (and have it call your office or conference phone)</span></span></li><li><span><span>Not working in a Pfizer office or using a mobile phone?</span></span><ul><li><span><span>From a<b>computer</b> with a good Internet connection, select </span></span><span><b><span>Call Using Computer+</span></b></span></li><li><span><span>From a<b>mobile device</b> with Wi-Fi access, select </span></span><span><b><span>Call Over Internet+</span></b></span></li><li><span><span>If no Internet or data connection is available, see below for dial-in details</span></span></li></ul></li></ul><p><span><span>+ Use a headset or mobile phone earbuds for the best quality sound</span></span></p><p><span><span><br><b>WebEx Meeting and Support Details</b><br>Meeting number: 171 435 1281</span></span>&nbsp;<span><span>Meeting password:</span></span><span><span>F3wPJFJjs86</span></span>&nbsp;<span><span><br><br></span></span><span><b><span>No Internet or data connection?</span></b></span><span><span><br></span></span><span><span>If you are located in a different country than the one shown, find your country's dial-in number using the<b>Global call-in numbers</b> link below - please use the <b>TOLL number</b>, if available:</span></span><span><span><br><br></span></span><span><b><span>Join by phone</span></b></span><span><span>&nbsp;<br></span></span><span><span>+1-415-527-5004&nbsp;Call-in toll number (US/Canada)</span></span><span><span>&nbsp;<br></span></span><span><span>Access code: 171 435 1281</span></span><span><span>&nbsp;<br></span></span><a href="https://collaborate.webex.com/collaborate/globalcallin.php?MTID=m02083c1861508bae21e51627a00fc327"><span><span>Global call-in numbers</span></span></a><span><span>&nbsp;&nbsp;|&nbsp;&nbsp;</span></span><a href="https://www.webex.com/pdf/tollfree_restrictions.pdf"><span><span>Toll-free calling restrictions</span></span></a> &nbsp;</p><span></span>
:END:
* Statistical rethinking book club - Chapter 3 & 4
  :PROPERTIES:
  :ETag:     "3202084525880000"
  :LOCATION: Webex
  :calendar-id: texhewson@gmail.com
  :ID:       _60q30c1g60o30e1i60o4ac1g60rj8gpl88rj2c1h84s34h9g60s30c1g60o30c1g8oo36e9j61148dq474p48dhg64o30c1g60o30c1g60o30c1g60o32c1g60o30c1g890kac1p64pkae258gpk2hhk68s3cci36gqjae9o8p246di58p10/texhewson@gmail.com
  :END:
:org-gcal:
<2020-09-25 Fri 15:00-16:00>



-- Do not delete or change any of the following text. --

1. Click to Join the Meeting<https://collaborate.webex.com/collaborate/j.php?MTID=m47aa775afdf20a87b7438398c6794a85>

IMPORTANT NOTICE: Please note that this Webex service allows audio and other information sent during the session to be recorded, which may be discoverable in a legal matter. By joining this session, you automatically consent to such recordings. If you do not consent to being recorded, discuss your concerns with the host or do not join the session.

2. Join the Audio

  *   From a Pfizer office - select Call Me (and have it call your office or conference phone)
  *   Not working in a Pfizer office or using a mobile phone?
     *   From a computer with a good Internet connection, select Call Using Computer+
     *   From a mobile device with Wi-Fi access, select Call Over Internet+
     *   If no Internet or data connection is available, see below for dial-in details
+ Use a headset or mobile phone earbuds for the best quality sound

WebEx Meeting and Support Details
Meeting number: 171 494 0210  Meeting password: KgeMMV7ad63

No Internet or data connection?
If you are located in a different country than the one shown, find your country's dial-in number using the Global call-in numbers link below - please use the TOLL number, if available:

Join by phone
+1-415-527-5004 Call-in toll number (US/Canada)
Access code: 171 494 0210
Global call-in numbers<https://collaborate.webex.com/collaborate/globalcallin.php?MTID=m359eeef0ee4374b663cdb8d9d061ff6e>  |  Toll-free calling restrictions<https://www.webex.com/pdf/tollfree_restrictions.pdf>



:END:

* Chimney Sweep
  :PROPERTIES:
  :ETag:     "3202937124748000"
  :HANGOUTS: [[https://meet.google.com/oyo-ihti-kad][Join Hangouts Meet]]
  :calendar-id: texhewson@gmail.com
  :ID:       2lmsn9q85blvlmvqrk7886cr12/texhewson@gmail.com
  :END:
:org-gcal:
<2020-11-21 Sat 09:00-10:00>
:END:
* Clase de español
  :PROPERTIES:
  :ETag:     "3202941046234000"
  :LOCATION: Skype
  :HANGOUTS: [[https://meet.google.com/nju-ffwo-jnz][Join Hangouts Meet]]
  :calendar-id: texhewson@gmail.com
  :ID:       7q13ep82q1qm6125ukvt9j2kcr/texhewson@gmail.com
  :END:
:org-gcal:
<2020-10-08 Thu 17:00-18:00>
:END:
* Statistical rethinking book club
  :PROPERTIES:
  :ETag:     "3203082679396000"
  :LOCATION: Webex
  :calendar-id: texhewson@gmail.com
  :ID:       _60q30c1g60o30e1i60o4ac1g60rj8gpl88rj2c1h84s34h9g60s30c1g60o30c1g6go36dq58h24ch1i74rk8dhg64o30c1g60o30c1g60o30c1g60o32c1g60o30c1g6cr36ca28p0j8h2588o46e9k70sj8g9k68sj8ea48oo3ec1h88sg/texhewson@gmail.com
  :END:
:org-gcal:
<2020-10-02 Fri 16:00-17:00>



-- Do not delete or change any of the following text. --

1. Click to Join the Meeting<https://collaborate.webex.com/collaborate/j.php?MTID=m8e689d973fdd801ff2e016c953bfe55e>

IMPORTANT NOTICE: Please note that this Webex service allows audio and other information sent during the session to be recorded, which may be discoverable in a legal matter. By joining this session, you automatically consent to such recordings. If you do not consent to being recorded, discuss your concerns with the host or do not join the session.

2. Join the Audio

  *   From a Pfizer office - select Call Me (and have it call your office or conference phone)
  *   Not working in a Pfizer office or using a mobile phone?
     *   From a computer with a good Internet connection, select Call Using Computer+
     *   From a mobile device with Wi-Fi access, select Call Over Internet+
     *   If no Internet or data connection is available, see below for dial-in details
+ Use a headset or mobile phone earbuds for the best quality sound

WebEx Meeting and Support Details
Meeting number: 171 198 2986  Meeting password: GNt2tCpPY52

No Internet or data connection?
If you are located in a different country than the one shown, find your country's dial-in number using the Global call-in numbers link below - please use the TOLL number, if available:

Join by phone
+1-415-527-5004 Call-in toll number (US/Canada)
Access code: 171 198 2986
Global call-in numbers<https://collaborate.webex.com/collaborate/globalcallin.php?MTID=m4e847bffe6ed77e9830c278762cf8e62>  |  Toll-free calling restrictions<https://www.webex.com/pdf/tollfree_restrictions.pdf>



:END:
* Statistical rethinking book club
  :PROPERTIES:
  :ETag:     "3203773763434000"
  :LOCATION: Webex
  :calendar-id: texhewson@gmail.com
  :ID:       _60q30c1g60o30e1i60o4ac1g60rj8gpl88rj2c1h84s34h9g60s30c1g60o30c1g6so30dhi6kokchi1750k8dhg64o30c1g60o30c1g60o30c1g60o32c1g60o30c1g711j6h258gqkad256or46g9k6p136d1m6csk2hi68p2jcd9g88og/texhewson@gmail.com
  :END:
:org-gcal:
<2020-10-09 Fri 15:00-16:00>

Hi all,

When we met on Friday we decided that since Chapters 6 and 7 were quite long, we would discuss only up to Chapter 7 by the end of this week, to give folks a chance to catch up.

Hope this time suits.
Mike


-- Do not delete or change any of the following text. --

1. Click to Join the Meeting<https://collaborate.webex.com/collaborate/j.php?MTID=m07d9e3a08593fbed1b48edf7ab248a13>

IMPORTANT NOTICE: Please note that this Webex service allows audio and other information sent during the session to be recorded, which may be discoverable in a legal matter. By joining this session, you automatically consent to such recordings. If you do not consent to being recorded, discuss your concerns with the host or do not join the session.

2. Join the Audio

  *   From a Pfizer office - select Call Me (and have it call your office or conference phone)
  *   Not working in a Pfizer office or using a mobile phone?

     *   From a computer with a good Internet connection, select Call Using Computer+
     *   From a mobile device with Wi-Fi access, select Call Over Internet+
     *   If no Internet or data connection is available, see below for dial-in details
+ Use a headset or mobile phone earbuds for the best quality sound

WebEx Meeting and Support Details
Meeting number: 171 094 0499  Meeting password: AMy8mbBsf85

No Internet or data connection?
If you are located in a different country than the one shown, find your country's dial-in number using the Global call-in numbers link below - please use the TOLL number, if available:

Join by phone
+1-415-527-5004 Call-in toll number (US/Canada)
Access code: 171 094 0499
Global call-in numbers<https://collaborate.webex.com/collaborate/globalcallin.php?MTID=md2b290273224821b48be86306cb891e7>  |  Toll-free calling restrictions<https://www.webex.com/pdf/tollfree_restrictions.pdf>



:END:
* Statistical rethinking book club
  :PROPERTIES:
  :ETag:     "3205022192930000"
  :LOCATION: Webex
  :calendar-id: texhewson@gmail.com
  :ID:       _60q30c1g60o30e1i60o4ac1g60rj8gpl88rj2c1h84s34h9g60s30c1g60o30c1g8go36d9h8osjee9j84o48dhg64o30c1g60o30c1g60o30c1g60o32c1g60o30c1g711j6h258gqkad256or46g9k6p136d1m6csk2hi68p2jcd9g88og/texhewson@gmail.com
  :END:
:org-gcal:
<2020-10-16 Fri 16:30-17:30>

Hi all,

Meeting again on Friday to catch up on Chapter 8 (Conditional Manatees / Interactions)

Hope this time suits.
Mike


-- Do not delete or change any of the following text. --

1. Click to Join the Meeting<https://collaborate.webex.com/collaborate/j.php?MTID=m07d9e3a08593fbed1b48edf7ab248a13>

IMPORTANT NOTICE: Please note that this Webex service allows audio and other information sent during the session to be recorded, which may be discoverable in a legal matter. By joining this session, you automatically consent to such recordings. If you do not consent to being recorded, discuss your concerns with the host or do not join the session.

2. Join the Audio

  *   From a Pfizer office - select Call Me (and have it call your office or conference phone)
  *   Not working in a Pfizer office or using a mobile phone?

     *   From a computer with a good Internet connection, select Call Using Computer+
     *   From a mobile device with Wi-Fi access, select Call Over Internet+
     *   If no Internet or data connection is available, see below for dial-in details
+ Use a headset or mobile phone earbuds for the best quality sound

WebEx Meeting and Support Details
Meeting number: 171 094 0499  Meeting password: AMy8mbBsf85

No Internet or data connection?
If you are located in a different country than the one shown, find your country's dial-in number using the Global call-in numbers link below - please use the TOLL number, if available:

Join by phone
+1-415-527-5004 Call-in toll number (US/Canada)
Access code: 171 094 0499
Global call-in numbers<https://collaborate.webex.com/collaborate/globalcallin.php?MTID=md2b290273224821b48be86306cb891e7>  |  Toll-free calling restrictions<https://www.webex.com/pdf/tollfree_restrictions.pdf>



:END:
* Statistical rethinking book club
  :PROPERTIES:
  :ETag:     "3205731138082000"
  :LOCATION: Webex
  :calendar-id: texhewson@gmail.com
  :ID:       _60q30c1g60o30e1i60o4ac1g60rj8gpl88rj2c1h84s34h9g60s30c1g60o30c1g8oo36h9h6sp4ch9h84pk8dhg64o30c1g60o30c1g60o30c1g60o32c1g60o30c1g711j6h258gqkad256or46g9k6p136d1m6csk2hi68p2jcd9g88og/texhewson@gmail.com
  :END:
:org-gcal:
<2020-10-23 Fri 15:00-16:00>



-- Do not delete or change any of the following text. --

1. Click to Join the Meeting<https://collaborate.webex.com/collaborate/j.php?MTID=m6d37fd4df1ea92ea2073e38812303dd3>

IMPORTANT NOTICE: Please note that this Webex service allows audio and other information sent during the session to be recorded, which may be discoverable in a legal matter. By joining this session, you automatically consent to such recordings. If you do not consent to being recorded, discuss your concerns with the host or do not join the session.

2. Join the Audio

  *   From a Pfizer office - select Call Me (and have it call your office or conference phone)
  *   Not working in a Pfizer office or using a mobile phone?
     *   From a computer with a good Internet connection, select Call Using Computer+
     *   From a mobile device with Wi-Fi access, select Call Over Internet+
     *   If no Internet or data connection is available, see below for dial-in details
+ Use a headset or mobile phone earbuds for the best quality sound

WebEx Meeting and Support Details
Meeting number: 171 423 6764  Meeting password: nH3V9SK3FZN

No Internet or data connection?
If you are located in a different country than the one shown, find your country's dial-in number using the Global call-in numbers link below - please use the TOLL number, if available:

Join by phone
+1-415-527-5004 Call-in toll number (US/Canada)
Access code: 171 423 6764
Global call-in numbers<https://collaborate.webex.com/collaborate/globalcallin.php?MTID=m46cb9284c8b99f288d3194f8e2a18a90>  |  Toll-free calling restrictions<https://www.webex.com/pdf/tollfree_restrictions.pdf>



:END:
* O'Neil Conjecture - Discussion
  :PROPERTIES:
  :ETag:     "3206559142058000"
  :HANGOUTS: [[https://meet.google.com/wvq-xwup-das][Join Hangouts Meet]]
  :calendar-id: texhewson@gmail.com
  :ID:       333hch8qgh34qe2nmlntb4t3lb/texhewson@gmail.com
  :END:
:org-gcal:
<2020-10-21 Wed 17:00-18:00>
:END:

* Clase de Español
  :PROPERTIES:
  :ETag:     "3206584578172000"
  :LOCATION: Skype
  :HANGOUTS: [[https://meet.google.com/dzb-pjrp-pux][Join Hangouts Meet]]
  :calendar-id: texhewson@gmail.com
  :ID:       25bidvu59m3rq7c2juk8jr90hc/texhewson@gmail.com
  :END:
:org-gcal:
<2020-10-27 Tue 16:00-17:00>
:END:
* HEOR
  :PROPERTIES:
  :ETag:     "3206584621600000"
  :calendar-id: texhewson@gmail.com
  :ID:       02edjjb2b77ehv32bvh4feulg1/texhewson@gmail.com
  :END:
:org-gcal:
<2020-10-27 Tue 14:00-15:00>
:END:

* Workout
  :PROPERTIES:
  :ETag:     "3206711647576000"
  :calendar-id: texhewson@gmail.com
  :ID:       54d09gkgn6s6f2nrc9tr1pg3li/texhewson@gmail.com
  :END:
:org-gcal:
<2020-10-22 Thu 13:30-14:30>
:END:
