#+CATEGORY: Calendar


* Mark Skelton's Zoom Meeting
  :PROPERTIES:
  :ETag:     "3182189618042000"
  :LOCATION: https://us02web.zoom.us/j/83722615875?pwd=VnUyVGQ5UG5mcVd2bm0wN2dsVjNhdz09
  :calendar-id: texhewson@gmail.com
  :ID:       _60q30c1g60o30e1i60o4ac1g60rj8gpl88rj2c1h84s34h9g60s30c1g60o30c1g70o4cc9g8d1kce9k6cr48dhg64o30c1g60o30c1g60o30c1g60o32c1g60o30c1g8gp46gi270pj0d9p6cpjgghk88s3ed1o60pj0cpi88p34c1i84qg_20201117T110000Z/texhewson@gmail.com
  :END:
:org-gcal:
<2020-11-17 Tue 11:00-11:45>

Mark Skelton is inviting you to a scheduled Zoom meeting.

Join Zoom Meeting
https://us02web.zoom.us/j/83722615875?pwd=VnUyVGQ5UG5mcVd2bm0wN2dsVjNhdz09

Meeting ID: 837 2261 5875
Password: Torbay

This email is confidential and intended solely for the use of the individual to whom it is addressed. Any views or opinions presented are solely those of the author and do not necessarily represent those of the Roman Catholic Diocese of Plymouth. If you are not the intended recipient, be advised that you have received this email in error and that any use, dissemination, forwarding, printing or copying of this email is strictly prohibited. If you have received this email in error please contact the sender.
:END:
* Chimney Sweep
  :PROPERTIES:
  :ETag:     "3202937124748000"
  :HANGOUTS: [[https://meet.google.com/oyo-ihti-kad][Join Hangouts Meet]]
  :calendar-id: texhewson@gmail.com
  :ID:       2lmsn9q85blvlmvqrk7886cr12/texhewson@gmail.com
  :END:
:org-gcal:
<2020-11-21 Sat 09:00-10:00>
:END:
* RSS Data Ethics SIG meeting
  :PROPERTIES:
  :ETag:     "3212961916162000"
  :LOCATION: Jitsi Meeting - https://meet.jit.si/NeatTitlesExportAstonishingly
  :HANGOUTS: [[https://meet.google.com/sgu-hace-phf][Join Hangouts Meet]]
  :calendar-id: texhewson@gmail.com
  :ID:       5ihp4q869eogg9drko3in5m4u9/texhewson@gmail.com
  :END:
:org-gcal:
<2020-11-26 Thu 15:30-17:30>


Click the following link to join the meeting from your computer: https://meet.jit.si/NeatTitlesExportAstonishingly

=====

Just want to dial in on your phone?

Call one of the following numbers:
Australia: +61.8.7150.1136
Brazil: +55.21.3500.0112
Canada: +1.437.538.3987
France: +33.1.87.21.0005
Germany: +49.89.380.38719
Japan: +81.3.4510.2372
Netherlands: +31.85.208.1541
Spain: +34.932.205.409
Switzerland: +41.61.588.0496
UK: +44.203.885.2179
US: +1.512.647.1431

Dial your meeting ID: '371104190' and you will be connected!
:END:
* Statistical rethinking
  :PROPERTIES:
  :ETag:     "3212965457436000"
  :LOCATION: Webex
  :calendar-id: texhewson@gmail.com
  :ID:       _60q30c1g60o30e1i60o4ac1g60rj8gpl88rj2c1h84s34h9g60s30c1g60o30c1g60o46h9g70ojgd2488q48dhg64o30c1g60o30c1g60o30c1g60o32c1g60o30c1g6h336c1m611jicho6t14ch9k6gs4ah9p74sk8d1l712j8dq38opg_20201120T140000Z/texhewson@gmail.com
  :END:
:org-gcal:
<2020-11-20 Fri 14:00-15:00>

[AgendaAssistantUserPromptImage]


-- Do not delete or change any of the following text. --

1. Click to Join the Meeting<https://collaborate.webex.com/collaborate/j.php?MTID=m2ee24e339a6345efb45cc51868c6de37>

IMPORTANT NOTICE: Please note that this Webex service allows audio and other information sent during the session to be recorded, which may be discoverable in a legal matter. By joining this session, you automatically consent to such recordings. If you do not consent to being recorded, discuss your concerns with the host or do not join the session.

2. Join the Audio

  *   From a Pfizer office - select Call Me (and have it call your office or conference phone)
  *   Not working in a Pfizer office or using a mobile phone?

     *   From a computer with a good Internet connection, select Call Using Computer+
     *   From a mobile device with Wi-Fi access, select Call Over Internet+
     *   If no Internet or data connection is available, see below for dial-in details
+ Use a headset or mobile phone earbuds for the best quality sound

WebEx Meeting and Support Details
Meeting number: 178 055 3007  Meeting password: TJaMVJuZ336

No Internet or data connection?
If you are located in a different country than the one shown, find your country's dial-in number using the Global call-in numbers link below - please use the TOLL number, if available:

Join by phone
+1-415-527-5004 Call-in toll number (US/Canada)
Access code: 178 055 3007
Global call-in numbers<https://collaborate.webex.com/collaborate/globalcallin.php?MTID=mfa9d783ab9232dff213962f7d25c9259>  |  Toll-free calling restrictions<https://www.webex.com/pdf/tollfree_restrictions.pdf>



:END:
* Statistical rethinking
  :PROPERTIES:
  :ETag:     "3212965457436000"
  :LOCATION: Webex
  :calendar-id: texhewson@gmail.com
  :ID:       _60q30c1g60o30e1i60o4ac1g60rj8gpl88rj2c1h84s34h9g60s30c1g60o30c1g60o46h9g70ojgd2488q48dhg64o30c1g60o30c1g60o30c1g60o32c1g60o30c1g6h336c1m611jicho6t14ch9k6gs4ah9p74sk8d1l712j8dq38opg_20201127T140000Z/texhewson@gmail.com
  :END:
:org-gcal:
<2020-11-27 Fri 14:00-15:00>

[AgendaAssistantUserPromptImage]


-- Do not delete or change any of the following text. --

1. Click to Join the Meeting<https://collaborate.webex.com/collaborate/j.php?MTID=m2ee24e339a6345efb45cc51868c6de37>

IMPORTANT NOTICE: Please note that this Webex service allows audio and other information sent during the session to be recorded, which may be discoverable in a legal matter. By joining this session, you automatically consent to such recordings. If you do not consent to being recorded, discuss your concerns with the host or do not join the session.

2. Join the Audio

  *   From a Pfizer office - select Call Me (and have it call your office or conference phone)
  *   Not working in a Pfizer office or using a mobile phone?

     *   From a computer with a good Internet connection, select Call Using Computer+
     *   From a mobile device with Wi-Fi access, select Call Over Internet+
     *   If no Internet or data connection is available, see below for dial-in details
+ Use a headset or mobile phone earbuds for the best quality sound

WebEx Meeting and Support Details
Meeting number: 178 055 3007  Meeting password: TJaMVJuZ336

No Internet or data connection?
If you are located in a different country than the one shown, find your country's dial-in number using the Global call-in numbers link below - please use the TOLL number, if available:

Join by phone
+1-415-527-5004 Call-in toll number (US/Canada)
Access code: 178 055 3007
Global call-in numbers<https://collaborate.webex.com/collaborate/globalcallin.php?MTID=mfa9d783ab9232dff213962f7d25c9259>  |  Toll-free calling restrictions<https://www.webex.com/pdf/tollfree_restrictions.pdf>



:END:
* Preliminary checks
  :PROPERTIES:
  :ETag:     "3210772391178000"
  :LOCATION: https://meetingsemea28.webex.com/meetingsemea28/j.php?MTID=mc89ed7e5a89ed83719e35811e35c629e
  :calendar-id: texhewson@gmail.com
  :ID:       _60s32ohoccqjabb4cgq68b9kc5im8bb1cli3cbb169j66dpp6gqm6chnc8/texhewson@gmail.com
  :END:
:org-gcal:
<2020-11-18 Wed 19:00-19:30>





JOIN WEBEX MEETING
https://meetingsemea28.webex.com/meetingsemea28/j.php?MTID=mc89ed7e5a89ed83719e35811e35c629e
Meeting number (access code): 175 490 9305

Meeting password: 2KMyAbb4h52 (25692224 from video systems)



JOIN BY PHONE
Use VoIP only


JOIN FROM A VIDEO SYSTEM OR APPLICATION
Dial sip:1754909305@meetingsemea28.webex.com
You can also dial 62.109.219.4 and enter your meeting number.


Join using Microsoft Lync or Microsoft Skype for Business
Dial sip:1754909305.meetingsemea28@lync.webex.com





Can't join the meeting?
https://collaborationhelp.cisco.com/article/WBX000029055


IMPORTANT NOTICE: Please note that this Webex service allows audio and other information sent during the session to be recorded, which may be discoverable in a legal matter. By joining this session, you automatically consent to such recordings. If you do not consent to being recorded, discuss your concerns with the host or do not join the session.
:END:
* Mathematics Cluster meeting
  :PROPERTIES:
  :ETag:     "3211039858690000"
  :calendar-id: texhewson@gmail.com
  :ID:       _60q30c1g60o30e1i60o4ac1g60rj8gpl88rj2c1h84s34h9g60s30c1g60o30c1g84pkce1j6h1jicq688s48dhg64o30c1g60o30c1g60o30c1g60o32c1g60o30c1g70rjcga36h2j6gi26kq30d9k60sk8gpn751k4ha48go38e9k8oo0/texhewson@gmail.com
  :END:
:org-gcal:
<2020-11-16 Mon 14:45-15:30>

Dear all,

Following the VC's statement earlier today I propose to hold a cluster meeting on Monday. In part to clarify our approach to delivery in December, but also to think ahead to TB2.

I think 14:45 - 15:30 should suit most people. Apologies for those for whom it does not (in which case I'll catch-up with those individuals after).

regards

Kevin



________________________________________________________________________________
Microsoft Teams meeting
Join on your computer or mobile app
Click here to join the meeting<https://teams.microsoft.com/l/meetup-join/19%3ameeting_NzhjNDg5OTItYTk3Zi00MzUwLTkyZGItMDQ3Y2U0YzhjYmVk%40thread.v2/0?context=%7b%22Tid%22%3a%2207ef1208-413c-4b5e-9cdd-64ef305754f0%22%2c%22Oid%22%3a%22622b3713-2004-44ad-b52e-53ec1541118b%22%7d>
Or call in (audio only)
+44 20 3821 1622,,255450466#<tel:+442038211622,,255450466#>   United Kingdom, London
Phone Conference ID: 255 450 466#
Find a local number<https://dialin.teams.microsoft.com/a2bdfce2-d36e-4a32-b2a3-dbebbfe02416?id=255450466> | Reset PIN<https://mysettings.lync.com/pstnconferencing>
[https://style.uwe.ac.uk/branding/twentytwenty/engine/images/logo.png]
Learn More<https://aka.ms/JoinTeamsMeeting> | Help<https://www1.uwe.ac.uk/its/itservicedesk.aspx> | Meeting options<https://teams.microsoft.com/meetingOptions/?organizerId=622b3713-2004-44ad-b52e-53ec1541118b&tenantId=07ef1208-413c-4b5e-9cdd-64ef305754f0&threadId=19_meeting_NzhjNDg5OTItYTk3Zi00MzUwLTkyZGItMDQ3Y2U0YzhjYmVk@thread.v2&messageId=0&language=en-GB> | Legal<https://www1.uwe.ac.uk/about/websiteinformation/privacy.aspx>
________________________________________________________________________________
:END:
* Peter/Paul - algorithm event
  :PROPERTIES:
  :ETag:     "3211047876346000"
  :LOCATION: https://meet.google.com/jum-bygo-kfw
  :HANGOUTS: [[https://meet.google.com/jum-bygo-kfw][Join Hangouts Meet]]
  :calendar-id: texhewson@gmail.com
  :ID:       5ehbuqgtdr7426mkl8tc3cacop/texhewson@gmail.com
  :END:
:org-gcal:
<2020-11-16 Mon 11:00-11:30>

https://meet.google.com/jum-bygo-kfw
:END:
* Peter/Paul - RSS event
  :PROPERTIES:
  :ETag:     "3213503413246000"
  :HANGOUTS: [[https://meet.google.com/run-uyth-agf][Join Hangouts Meet]]
  :calendar-id: texhewson@gmail.com
  :ID:       65rto3v046u8qejjm3fj9ljqnf/texhewson@gmail.com
  :END:
:org-gcal:
<2020-11-30 Mon 16:00-16:30>
:END:
* Open evening
  :PROPERTIES:
  :ETag:     "3215071879770000"
  :calendar-id: texhewson@gmail.com
  :ID:       70pjiopic8qj0b9m6som4b9kc4o64b9oc4pj4b9hc8q34d1nckq3ip1mc8/texhewson@gmail.com
  :END:
:org-gcal:
<2020-12-09 Wed 18:00-19:00>

https://apply.army.mod.uk/what-we-offer/regular-soldier/training/afcharrogate
:END:
* Business studies tutorial
  :PROPERTIES:
  :ETag:     "3211252742668000"
  :calendar-id: texhewson@gmail.com
  :ID:       4987mbirer6opdc9kg8rqch7qn_20201127T100000Z/texhewson@gmail.com
  :END:
:org-gcal:
<2020-11-27 Fri 10:00-11:00>
:END:
* Business studies tutorial
  :PROPERTIES:
  :ETag:     "3211252742668000"
  :calendar-id: texhewson@gmail.com
  :ID:       4987mbirer6opdc9kg8rqch7qn_20201204T100000Z/texhewson@gmail.com
  :END:
:org-gcal:
<2020-12-04 Fri 10:00-11:00>
:END:
* Business studies tutorial
  :PROPERTIES:
  :ETag:     "3211252816636000"
  :calendar-id: texhewson@gmail.com
  :ID:       25ofgf3ttc34u2cqbtcht0u6ah_20201127T110000Z/texhewson@gmail.com
  :END:
:org-gcal:
<2020-11-27 Fri 11:00-12:00>
:END:
* Business studies tutorial
  :PROPERTIES:
  :ETag:     "3211252816636000"
  :calendar-id: texhewson@gmail.com
  :ID:       25ofgf3ttc34u2cqbtcht0u6ah_20201204T110000Z/texhewson@gmail.com
  :END:
:org-gcal:
<2020-12-04 Fri 11:00-12:00>
:END:
* Business studies tutorial
  :PROPERTIES:
  :ETag:     "3211252849606000"
  :calendar-id: texhewson@gmail.com
  :ID:       5gak93pkisunvasi47sgsul1h0_20201127T130000Z/texhewson@gmail.com
  :END:
:org-gcal:
<2020-11-27 Fri 13:00-14:00>
:END:
* Business studies tutorial
  :PROPERTIES:
  :ETag:     "3211252849606000"
  :calendar-id: texhewson@gmail.com
  :ID:       5gak93pkisunvasi47sgsul1h0_20201204T130000Z/texhewson@gmail.com
  :END:
:org-gcal:
<2020-12-04 Fri 13:00-14:00>
:END:
* Business studies tutorial
  :PROPERTIES:
  :ETag:     "3211252916726000"
  :calendar-id: texhewson@gmail.com
  :ID:       340l3pvaalf5etti0arrad7h09/texhewson@gmail.com
  :END:
:org-gcal:
<2020-12-02 Wed 13:00-14:00>
:END:
* Week 20
  :PROPERTIES:
  :ETag:     "3211252963962000"
  :calendar-id: texhewson@gmail.com
  :ID:       12ef9t3g4m8dtp4h07fvar3slk/texhewson@gmail.com
  :END:
:org-gcal:
<2020-11-23 Mon 08:00-09:00>
:END:

* Business studies tutorial (online?) UMCDM8
  :PROPERTIES:
  :ETag:     "3211253403104000"
  :calendar-id: texhewson@gmail.com
  :ID:       104pd9g51ha3oh1ejavein1333/texhewson@gmail.com
  :END:
:org-gcal:
<2020-11-30 Mon 09:30-10:30>
:END:
* Business studies tutorial (online?)  UMCDM8
  :PROPERTIES:
  :ETag:     "3211253427470000"
  :calendar-id: texhewson@gmail.com
  :ID:       2cjuau85rlrl65lb5msot5cnsi/texhewson@gmail.com
  :END:
:org-gcal:
<2020-11-30 Mon 13:00-14:00>
:END:
* Business studies tutorial (online?)  UMCDM8
  :PROPERTIES:
  :ETag:     "3211253448742000"
  :calendar-id: texhewson@gmail.com
  :ID:       464v5m16pmu38l5hdolqvdu1ge/texhewson@gmail.com
  :END:
:org-gcal:
<2020-11-30 Mon 14:00-15:00>
:END:
* Business studies tutorial (online?)  UMCDM8
  :PROPERTIES:
  :ETag:     "3211253479250000"
  :calendar-id: texhewson@gmail.com
  :ID:       3g2jrqnof0drvk1s9bli5jnh5i/texhewson@gmail.com
  :END:
:org-gcal:
<2020-12-01 Tue 09:00-10:00>
:END:
* Business studies tutorial (online?)  UMCDM8
  :PROPERTIES:
  :ETag:     "3211253500328000"
  :calendar-id: texhewson@gmail.com
  :ID:       7dhk2i8srkohtg6a5ul1tlr5t1/texhewson@gmail.com
  :END:
:org-gcal:
<2020-12-01 Tue 11:00-12:00>
:END:
* Business studies tutorial (online?)  UMCDM8
  :PROPERTIES:
  :ETag:     "3211253521148000"
  :calendar-id: texhewson@gmail.com
  :ID:       26viukcqgpr2vhru5jugj1se6i/texhewson@gmail.com
  :END:
:org-gcal:
<2020-12-01 Tue 12:00-13:00>
:END:
* Business tutorial UMCDM9
  :PROPERTIES:
  :ETag:     "3211253676518000"
  :calendar-id: texhewson@gmail.com
  :ID:       6ttcavr2nen43srgknno90jra2_20210104T090000Z/texhewson@gmail.com
  :END:
:org-gcal:
<2021-01-04 Mon 09:00-10:00>
:END:
* Business tutorial UMCDM9
  :PROPERTIES:
  :ETag:     "3211253676518000"
  :calendar-id: texhewson@gmail.com
  :ID:       6ttcavr2nen43srgknno90jra2_20210111T090000Z/texhewson@gmail.com
  :END:
:org-gcal:
<2021-01-11 Mon 09:00-10:00>
:END:
* Business studies tutorial UMCDB9
  :PROPERTIES:
  :ETag:     "3211253758550000"
  :calendar-id: texhewson@gmail.com
  :ID:       5ut35bl9e8kesm62om5ijtm3af_20210104T100000Z/texhewson@gmail.com
  :END:
:org-gcal:
<2021-01-04 Mon 10:00-11:00>
:END:
* Business studies tutorial UMCDB9
  :PROPERTIES:
  :ETag:     "3211253758550000"
  :calendar-id: texhewson@gmail.com
  :ID:       5ut35bl9e8kesm62om5ijtm3af_20210111T100000Z/texhewson@gmail.com
  :END:
:org-gcal:
<2021-01-11 Mon 10:00-11:00>
:END:
* Business studies tutorial UMCDM8
  :PROPERTIES:
  :ETag:     "3211253870272000"
  :calendar-id: texhewson@gmail.com
  :ID:       1taqp04uu4u2br8tutf7rnq6ik_20210104T120000Z/texhewson@gmail.com
  :END:
:org-gcal:
<2021-01-04 Mon 12:00-13:00>
:END:
* Business tutorial UMCDB9
  :PROPERTIES:
  :ETag:     "3211254106634000"
  :calendar-id: texhewson@gmail.com
  :ID:       4lops5n3d32lp7fr89i6vm491n_20210106T093000Z/texhewson@gmail.com
  :END:
:org-gcal:
<2021-01-06 Wed 09:30-10:30>
:END:
* Business tutorial UMCDB9
  :PROPERTIES:
  :ETag:     "3211254106634000"
  :calendar-id: texhewson@gmail.com
  :ID:       4lops5n3d32lp7fr89i6vm491n_20210113T093000Z/texhewson@gmail.com
  :END:
:org-gcal:
<2021-01-13 Wed 09:30-10:30>
:END:
* Business tutorial UMCDB9
  :PROPERTIES:
  :ETag:     "3211254173100000"
  :calendar-id: texhewson@gmail.com
  :ID:       7p9sq3esmmi7oqagk797smk980_20210106T140000Z/texhewson@gmail.com
  :END:
:org-gcal:
<2021-01-06 Wed 14:00-15:00>
:END:
* Business tutorial UMCDB9
  :PROPERTIES:
  :ETag:     "3211254173100000"
  :calendar-id: texhewson@gmail.com
  :ID:       7p9sq3esmmi7oqagk797smk980_20210113T140000Z/texhewson@gmail.com
  :END:
:org-gcal:
<2021-01-13 Wed 14:00-15:00>
:END:
* Business tutorial UMCMB9
  :PROPERTIES:
  :ETag:     "3211254474610000"
  :calendar-id: texhewson@gmail.com
  :ID:       3i6o043t7soqs6h31jjbc4kjnd_20210106T150000Z/texhewson@gmail.com
  :END:
:org-gcal:
<2021-01-06 Wed 15:00-16:00>
:END:
* Business tutorial UMCMB9
  :PROPERTIES:
  :ETag:     "3211254474610000"
  :calendar-id: texhewson@gmail.com
  :ID:       3i6o043t7soqs6h31jjbc4kjnd_20210113T150000Z/texhewson@gmail.com
  :END:
:org-gcal:
<2021-01-13 Wed 15:00-16:00>
:END:

* Overnight
  :PROPERTIES:
  :ETag:     "3211737026844000"
  :calendar-id: texhewson@gmail.com
  :ID:       c5i68d9p6gsj2bb26ks3gb9kchim2b9pc9gm6bb4c4s68e1m6osj2or174/texhewson@gmail.com
  :END:
:org-gcal:
<2020-11-26 Thu 19:00>--<2020-11-27 Fri 11:00>

https://www.google.com/travel/trips/trip?gsas=1&dest_src=utn&trip_id=1683870398448890255:1683870398448890255
:END:
* Remotely Invigilated Online Exams
  :PROPERTIES:
  :ETag:     "3212098235136000"
  :LOCATION: https://eqam.my.webex.com/eqam.my/j.php?MTID=m0b086a937c2138b29cf0f72a2ec63563
  :calendar-id: texhewson@gmail.com
  :ID:       _c5i3ad1n60rj8b9hchi3gb9k6him8bb2c8p6cb9n68s62c1i6phm4opp6o/texhewson@gmail.com
  :END:
:org-gcal:
<2020-11-22 Sun 18:20-19:40>





JOIN WEBEX MEETING
https://eqam.my.webex.com/eqam.my/j.php?MTID=m0b086a937c2138b29cf0f72a2ec63563
Meeting number (access code): 175 559 8239

Meeting password: M0OBW (60629 from phones and video systems)



TAP TO JOIN FROM A MOBILE DEVICE (ATTENDEES ONLY)
+44-20-7660-8149,,1755598239#60629# tel:%2B44-20-7660-8149,,*01*1755598239%2360629%23*01* United Kingdom Toll
Some mobile devices may ask attendees to enter a numeric meeting password.


JOIN BY PHONE
+44-20-7660-8149 United Kingdom Toll

Global call-in numbers
https://eqam.my.webex.com/eqam.my/globalcallin.php?MTID=m2fc844cceab7b6fc67a7064ebef7bafc


JOIN BY VIDEO SYSTEM, APPLICATION OR SKYPE FOR BUSINESS
Dial sip:1755598239@webex.com
You can also dial 62.109.219.4 and enter your meeting number.





Can't join the meeting?
https://collaborationhelp.cisco.com/article/WBX000029055


IMPORTANT NOTICE: Please note that this Webex service allows audio and other information sent during the session to be recorded, which may be discoverable in a legal matter. By joining this session, you automatically consent to such recordings. If you do not consent to being recorded, discuss your concerns with the host or do not join the session.
:END:
* MSc teaching
  :PROPERTIES:
  :ETag:     "3213825707178000"
  :calendar-id: texhewson@gmail.com
  :ID:       6hgmac1m75hmcbb66tj6cb9k6ormabb16lh3gb9l6kq66php6oo36cpl74/texhewson@gmail.com
  :END:
:org-gcal:
<2020-12-02 Wed 14:30-15:30>
:END:
* Co-op Christmas drinks
  :PROPERTIES:
  :ETag:     "3213999172386000"
  :calendar-id: texhewson@gmail.com
  :ID:       3ek50brda33b8a2jt5qra0hb7f/texhewson@gmail.com
  :END:
:org-gcal:
<2020-12-10 Thu 19:00-20:00>

<a href="https://gmail.us3.list-manage.com/track/click?u=4d23d81e0b5ed69484e234221&amp;id=a0aae4b8e6&amp;e=2eced5eb2c">https://us02web.zoom.us/j/<wbr>88969420045?pwd=<wbr>UnBUb0NTdmRpdzl3bUpUYmJYRjZMUT<wbr>09</a>
:END:
* Statistical rethinking book club
  :PROPERTIES:
  :ETag:     "3214155319662000"
  :LOCATION: Webex
  :calendar-id: texhewson@gmail.com
  :ID:       _60q30c1g60o30e1i60o4ac1g60rj8gpl88rj2c1h84s34h9g60s30c1g60o30c1g8ko36di38p2j0chn8d0k8dhg64o30c1g60o30c1g60o30c1g60o32c1g60o30c1g6t2k6ha48gqj6gq4650k6d9k8os4cc2164rjcdi275134cq66oqg_20201204T140000Z/texhewson@gmail.com
  :END:
:org-gcal:
<2020-12-04 Fri 14:00-15:00>

[AgendaAssistantUserPromptImage]


-- Do not delete or change any of the following text. --

1. Click to Join the Meeting<https://collaborate.webex.com/collaborate/j.php?MTID=m34d0bc5e3d52a0bc5f832cf9bd6a13f0>

IMPORTANT NOTICE: Please note that this Webex service allows audio and other information sent during the session to be recorded, which may be discoverable in a legal matter. By joining this session, you automatically consent to such recordings. If you do not consent to being recorded, discuss your concerns with the host or do not join the session.

2. Join the Audio

  *   From a Pfizer office - select Call Me (and have it call your office or conference phone)
  *   Not working in a Pfizer office or using a mobile phone?

     *   From a computer with a good Internet connection, select Call Using Computer+
     *   From a mobile device with Wi-Fi access, select Call Over Internet+
     *   If no Internet or data connection is available, see below for dial-in details
+ Use a headset or mobile phone earbuds for the best quality sound

WebEx Meeting and Support Details
Meeting number: 178 599 5767  Meeting password: 7BBpvZNhf82

No Internet or data connection?
If you are located in a different country than the one shown, find your country's dial-in number using the Global call-in numbers link below - please use the TOLL number, if available:

Join by phone
+1-415-527-5004 Call-in toll number (US/Canada)
Access code: 178 599 5767
Global call-in numbers<https://collaborate.webex.com/collaborate/globalcallin.php?MTID=m59166fd60b57b12ea9a28dee0ce75096>  |  Toll-free calling restrictions<https://www.webex.com/pdf/tollfree_restrictions.pdf>



:END:
* Statistical rethinking book club
  :PROPERTIES:
  :ETag:     "3214155319662000"
  :LOCATION: Webex
  :calendar-id: texhewson@gmail.com
  :ID:       _60q30c1g60o30e1i60o4ac1g60rj8gpl88rj2c1h84s34h9g60s30c1g60o30c1g8ko36di38p2j0chn8d0k8dhg64o30c1g60o30c1g60o30c1g60o32c1g60o30c1g6t2k6ha48gqj6gq4650k6d9k8os4cc2164rjcdi275134cq66oqg_20201218T140000Z/texhewson@gmail.com
  :END:
:org-gcal:
<2020-12-18 Fri 14:00-15:00>

[AgendaAssistantUserPromptImage]


-- Do not delete or change any of the following text. --

1. Click to Join the Meeting<https://collaborate.webex.com/collaborate/j.php?MTID=m34d0bc5e3d52a0bc5f832cf9bd6a13f0>

IMPORTANT NOTICE: Please note that this Webex service allows audio and other information sent during the session to be recorded, which may be discoverable in a legal matter. By joining this session, you automatically consent to such recordings. If you do not consent to being recorded, discuss your concerns with the host or do not join the session.

2. Join the Audio

  *   From a Pfizer office - select Call Me (and have it call your office or conference phone)
  *   Not working in a Pfizer office or using a mobile phone?

     *   From a computer with a good Internet connection, select Call Using Computer+
     *   From a mobile device with Wi-Fi access, select Call Over Internet+
     *   If no Internet or data connection is available, see below for dial-in details
+ Use a headset or mobile phone earbuds for the best quality sound

WebEx Meeting and Support Details
Meeting number: 178 599 5767  Meeting password: 7BBpvZNhf82

No Internet or data connection?
If you are located in a different country than the one shown, find your country's dial-in number using the Global call-in numbers link below - please use the TOLL number, if available:

Join by phone
+1-415-527-5004 Call-in toll number (US/Canada)
Access code: 178 599 5767
Global call-in numbers<https://collaborate.webex.com/collaborate/globalcallin.php?MTID=m59166fd60b57b12ea9a28dee0ce75096>  |  Toll-free calling restrictions<https://www.webex.com/pdf/tollfree_restrictions.pdf>



:END:
* FW: Deanery Meeting
  :PROPERTIES:
  :ETag:     "3214858826658000"
  :LOCATION: https://us02web.zoom.us/j/83382455195?pwd=c2pTOW1BZDBvcGhhZ3dxeUhSWFFpUT09
  :calendar-id: texhewson@gmail.com
  :ID:       _60q30c1g60o30e1i60o4ac1g60rj8gpl88rj2c1h84s34h9g60s30c1g60o30c1g6go32e9o60ojgd9p8d248dhg64o30c1g60o30c1g60o30c1g60o32c1g60o30c1g74qj0d1m8l0j2dpn8h1jacpk6cs3eh1j8oq42d1p60s44g9j710g/texhewson@gmail.com
  :END:
:org-gcal:
<2020-12-17 Thu 15:00-16:00>




Mark Skelton is inviting you to a scheduled Zoom meeting.

Join Zoom Meeting
https://us02web.zoom.us/j/83382455195?pwd=c2pTOW1BZDBvcGhhZ3dxeUhSWFFpUT09

Meeting ID: 833 8245 5195
Passcode: 955396
One tap mobile
+13462487799,,83382455195#,,,,,,0#,,955396# US (Houston)
+14086380968,,83382455195#,,,,,,0#,,955396# US (San Jose)

Dial by your location
        +1 346 248 7799 US (Houston)
        +1 408 638 0968 US (San Jose)
        +1 646 876 9923 US (New York)
        +1 669 900 6833 US (San Jose)
        +1 253 215 8782 US (Tacoma)
        +1 301 715 8592 US (Washington D.C)
        +1 312 626 6799 US (Chicago)
Meeting ID: 833 8245 5195
Passcode: 955396
Find your local number: https://us02web.zoom.us/u/kcoksiCm9R

This email is confidential and intended solely for the use of the individual to whom it is addressed. Any views or opinions presented are solely those of the author and do not necessarily represent those of the Roman Catholic Diocese of Plymouth. If you are not the intended recipient, be advised that you have received this email in error and that any use, dissemination, forwarding, printing or copying of this email is strictly prohibited. If you have received this email in error please contact the sender.
:END:
* Data Ethics SIG committee meeting
  :PROPERTIES:
  :ETag:     "3215074047638000"
  :LOCATION: Microsoft Teams Meeting
  :calendar-id: texhewson@gmail.com
  :ID:       _60q30c1g60o30e1i60o4ac1g60rj8gpl88rj2c1h84s34h9g60s30c1g60o30c1g6ko3gh25652kcd1l8d2k8dhg64o30c1g60o30c1g60o30c1g60o32c1g60o30c1g6d0k4cpj8h142g9o6533egpk6p138ha38h1jccpp612k4chl6osg/texhewson@gmail.com
  :END:
:org-gcal:
<2020-12-16 Wed 15:00-17:00>

Dear Paul,

Please see below the joining instructions for the Data Ethics SIG committee meeting on 16 December at 3pm.

Kind regards,
Amaka
________________________________________________________________________________
Microsoft Teams meeting
Join on your computer or mobile app
Click here to join the meeting<https://teams.microsoft.com/l/meetup-join/19%3ameeting_MWY2NDU4MGItNzg1OS00YWNhLTgyMjItZDQ4ZTNiM2E2MGUx%40thread.v2/0?context=%7b%22Tid%22%3a%22d7af58d0-d14d-4a14-b333-3d6d769ced80%22%2c%22Oid%22%3a%221af18ab4-9c7c-42c4-9cf3-bb0fc3551ad4%22%7d>
Or call in (audio only)
+44 20 3321 5256,,243254412#<tel:+442033215256,,243254412#>   United Kingdom, London
Phone Conference ID: 243 254 412#
Find a local number<https://dialin.teams.microsoft.com/4b5b6005-9bc2-431f-8de9-92e6a0c045c2?id=243254412> | Reset PIN<https://mysettings.lync.com/pstnconferencing>
[https://rss.org.uk/RSS/media/About/RSS-strapline-logo.jpg]
For dial-in instructions please click on Help
Learn More<https://aka.ms/JoinTeamsMeeting> | Help<https://rss.org.uk/training-events/events/webinars/dial/> | Meeting options<https://teams.microsoft.com/meetingOptions/?organizerId=1af18ab4-9c7c-42c4-9cf3-bb0fc3551ad4&tenantId=d7af58d0-d14d-4a14-b333-3d6d769ced80&threadId=19_meeting_MWY2NDU4MGItNzg1OS00YWNhLTgyMjItZDQ4ZTNiM2E2MGUx@thread.v2&messageId=0&language=en-US> | Legal<https://rss.org.uk/about/policy-and-guidelines/>
________________________________________________________________________________

:END:
* Statistical rethinking book club
  :PROPERTIES:
  :ETag:     "3215189969390000"
  :LOCATION: Webex
  :calendar-id: texhewson@gmail.com
  :ID:       _60q30c1g60o30e1i60o4ac1g60rj8gpl88rj2c1h84s34h9g60s30c1g60o30c1g8ko36di38p2j0chn8d0k8dhg64o30c1g60o30c1g60o30c1g60o32c1g60o30c1g6t2k6ha48gqj6gq4650k6d9k8os4cc2164rjcdi275134cq66oqg_20201211T140000Z/texhewson@gmail.com
  :END:
:org-gcal:
<2020-12-11 Fri 15:00-16:00>

UPDATE: I’m afraid I have an important meeting that I have to attend at 2pm GMT on Friday. Can we move this out by an hour?

Chapter 14 is a rather hefty read. If anybody wants to take an extra week over it, I’m OK to cancel for this week and reconvene next week.


-- Do not delete or change any of the following text. --

1. Click to Join the Meeting<https://collaborate.webex.com/collaborate/j.php?MTID=m419728833a799265a715a74830517379>

IMPORTANT NOTICE: Please note that this Webex service allows audio and other information sent during the session to be recorded, which may be discoverable in a legal matter. By joining this session, you automatically consent to such recordings. If you do not consent to being recorded, discuss your concerns with the host or do not join the session.

2. Join the Audio

  *   From a Pfizer office - select Call Me (and have it call your office or conference phone)
  *   Not working in a Pfizer office or using a mobile phone?

     *   From a computer with a good Internet connection, select Call Using Computer+
     *   From a mobile device with Wi-Fi access, select Call Over Internet+
     *   If no Internet or data connection is available, see below for dial-in details
+ Use a headset or mobile phone earbuds for the best quality sound

WebEx Meeting and Support Details
Meeting number: 178 949 7862  Meeting password: 7BBpvZNhf82

No Internet or data connection?
If you are located in a different country than the one shown, find your country's dial-in number using the Global call-in numbers link below - please use the TOLL number, if available:

Join by phone
+1-415-527-5004 Call-in toll number (US/Canada)
Access code: 178 949 7862
Global call-in numbers<https://collaborate.webex.com/collaborate/globalcallin.php?MTID=m464ef2a986dfff74330b0c60a0e05a4f>  |  Toll-free calling restrictions<https://www.webex.com/pdf/tollfree_restrictions.pdf>



:END:
* RSS Data Ethics SIG meeting
  :PROPERTIES:
  :ETag:     "3215140358561000"
  :LOCATION: RSS Microsoft Teams
  :calendar-id: texhewson@gmail.com
  :ID:       60s68e1kcli34bb36tijab9kcdim8b9p6hijcb9p6krj2pj3ccs36c356g/texhewson@gmail.com
  :END:
:org-gcal:
<2020-12-16 Wed 15:00-17:00>

<span>Microsoft Teams meeting<br>Join on your computer or mobile app<br>Click here to join the meeting&lt;<a href="https://teams.microsoft.com/l/meetup-join/19%3ameeting_MWY2NDU4MGItNzg1OS00YWNhLTgyMjItZDQ4ZTNiM2E2MGUx%40thread.v2/0?context=%7b%22Tid%22%3a%22d7af58d0-d14d-4a14-b333-3d6d769ced80%22%2c%22Oid%22%3a%221af18ab4-9c7c-42c4-9cf3-bb0fc3551ad4%22%7d">https://teams.microsoft.com/l/meetup-join/19%3ameeting_MWY2NDU4MGItNzg1OS00YWNhLTgyMjItZDQ4ZTNiM2E2MGUx%40thread.v2/0?context=%7b%22Tid%22%3a%22d7af58d0-d14d-4a14-b333-3d6d769ced80%22%2c%22Oid%22%3a%221af18ab4-9c7c-42c4-9cf3-bb0fc3551ad4%22%7d</a>&gt;<br>Or call in (audio only)<br>+44 20 3321 5256,,243254412#&lt;tel:+442033215256,,243254412#&gt;   United Kingdom, London<br>Phone Conference ID: 243 254 412#<br>Find a local number&lt;<a href="https://dialin.teams.microsoft.com/4b5b6005-9bc2-431f-8de9-92e6a0c045c2?id=243254412">https://dialin.teams.microsoft.com/4b5b6005-9bc2-431f-8de9-92e6a0c045c2?id=243254412</a>&gt; | Reset PIN&lt;<a href="https://mysettings.lync.com/pstnconferencing">https://mysettings.lync.com/pstnconferencing</a>&gt;<br>[<a href="https://rss.org.uk/RSS/media/About/RSS-strapline-logo.jpg">https://rss.org.uk/RSS/media/About/RSS-strapline-logo.jpg</a>]<br>For dial-in instructions please click on Help<br>Learn More&lt;<a href="https://aka.ms/JoinTeamsMeeting">https://aka.ms/JoinTeamsMeeting</a>&gt; | Help&lt;<a href="https://rss.org.uk/training-events/events/webinars/dial/">https://rss.org.uk/training-events/events/webinars/dial/</a>&gt; | Meeting options&lt;<a href="https://teams.microsoft.com/meetingOptions/?organizerId=1af18ab4-9c7c-42c4-9cf3-bb0fc3551ad4&tenantId=d7af58d0-d14d-4a14-b333-3d6d769ced80&threadId=19_meeting_MWY2NDU4MGItNzg1OS00YWNhLTgyMjItZDQ4ZTNiM2E2MGUx@thread.v2&messageId=0&language=en-US">https://teams.microsoft.com/meetingOptions/?organizerId=1af18ab4-9c7c-42c4-9cf3-bb0fc3551ad4&amp;tenantId=d7af58d0-d14d-4a14-b333-3d6d769ced80&amp;threadId=19_meeting_MWY2NDU4MGItNzg1OS00YWNhLTgyMjItZDQ4ZTNiM2E2MGUx@thread.v2&amp;messageId=0&amp;language=en-US</a>&gt; | Legal&lt;<a href="https://rss.org.uk/about/policy-and-guidelines/">https://rss.org.uk/about/policy-and-guidelines/</a>&gt;</span>
:END:
* [#B] Development Analytics - Consultant Roster  (Paul Hewson)
  :PROPERTIES:
  :ETag:     "3215409134208000"
  :LOCATION: Zoom
  :HANGOUTS: [[https://meet.google.com/ezg-qpag-kzk][Join Hangouts Meet]]
  :calendar-id: texhewson@gmail.com
  :ID:       kvoqrn0jp1ovlgfdottn8m4j3o/texhewson@gmail.com
  :END:
:org-gcal:
<2020-12-14 Mon 10:30-11:00>

As invited by your email<b>Zoom Meeting details:&nbsp;</b><br><br>Topic: Development Analytics Consultant Roster Introductions<br><p>Meeting ID: 327 157 3541<br>Security Passcode: 12345<br>Join URL:&nbsp;<a href="https://www.developmentanalytics.org/so/82NOU2dti/c?w=TcC5I21RXkqZEhmtnTrU9HZs6pIAq6zqqg3xcNlQxgI.eyJ1IjoiaHR0cHM6Ly91czAyd2ViLnpvb20udXMvai8zMjcxNTczNTQxP3B3ZD1NSGRxVlVwcmVXeDNURVU0V0UxTmVHRndjWE5SWnowOSIsInIiOiI4ZjU2NzViZC0yZTAzLTQyMzEtZjc1YS1jODc0MmQ5OThkOGMiLCJtIjoibWFpbCIsImMiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDAifQ">https://us02web.zoom.us/<u></u>j/3271573541pwd=<u></u>MHdqVUpreWx3TEU4WE1NeGFwcXNRZz<u></u>09</a></p>
:END:
