---
- hosts: all
  become: true
  tasks:

  - name: apt get update
    apt:
      update_cache: yes
      upgrade: yes

  - name: install known dependencies
    apt:
      name: ['gnupg', 'apt-transport-https', 'postgresql-client', 'libgeos-dev', 'libpq-dev', 'xorg']

  - name: sign apt
    apt_key:
      keyserver: keys.gnupg.net
      id: E19F5F87128899B192B1A2C2AD5F960A256A04AF

  - apt_repository:
      repo: deb https://www.stats.bris.ac.uk/R/bin/linux/debian buster-cran35/
      state: present
      update_cache: yes

  - name: install R
    apt:
      name: ['r-base', 'r-base-dev', 'r-base-core']

  - name: install R packages
    apt:
      name: ['r-cran-rpostgresql', 'r-cran-rcpp', 'r-cran-tidyverse']

  - name: Install more packages
    shell: R -e 'install.packages("{{ item }}")'
    with_items:
      sp
      raster
      rpostgis

  - name: pre install R studio server
    apt:
      name: ['gdebi-core', 'dpkg-sig']

  - name: download R studio server
    shell: wget https://download2.rstudio.org/server/bionic/amd64/rstudio-server-1.2.5033-amd64.deb

  - name: sign apt for R studio server
    apt_key:
      keyserver: keys.gnupg.net
      id: 3F32EE77E331692F

  - name: verify
    shell: dpkg-sig --verify rstudio-server-1.2.5033-amd64.deb

  - name: install R studio server
    shell: gdebi rstudio-server-1.2.5033-amd64.deb
